In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [2]:
# models

#linear models
from sklearn.linear_model import LinearRegression, Ridge, Lasso

#support vector regressor
from sklearn.svm import SVR

#knn
from sklearn.neighbors import KNeighborsRegressor

#decision trees
from sklearn.tree import DecisionTreeRegressor

#hyper parameter tuning
from sklearn.model_selection import RandomizedSearchCV

#ensemble techniques
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from xgboost import XGBRegressor

#evaluation techniques
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [3]:
# tain and test split model
from sklearn.model_selection import train_test_split

#scalar
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

# column transformer
from sklearn.compose import ColumnTransformer

In [4]:
# avoiding warnings
import warnings
warnings.filterwarnings("ignore")

In [5]:
from pathlib import Path
file = Path().cwd() / "data" / "stud.csv"

df = pd.read_csv(file)
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
# independent and dependent features
X = df.drop("math_score", axis=1)
y = df["math_score"]

In [7]:
# train and test split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=43)

In [8]:
cat_cols = X.select_dtypes(include="object").columns
num_cols = X.select_dtypes(exclude="object").columns

In [9]:
scaler = StandardScaler()
oh_encoder = OneHotEncoder()

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", oh_encoder, cat_cols),
        ("num", scaler, num_cols)
    ]
)

x_train_new = preprocessor.fit_transform(x_train)
x_test_new  = preprocessor.transform(x_test)

In [10]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [11]:
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
    "XGBRegressor": XGBRegressor(), 
    "AdaBoost Regressor": AdaBoostRegressor()
}

model_list = []
r2_list =[]

for name,model in models.items():
    # fitting the model
    model.fit(x_train_new, y_train)
    
    # get the prediction
    y_train_pred = model.predict(x_train_new)
    y_test_pred = model.predict(x_test_new)
    
    # evaluation
    mse_train, rmse_train, r2_train = evaluate_model(y_train, y_train_pred)
    mse_test, rmse_test, r2_test = evaluate_model(y_test, y_test_pred)
    
    model_list.append(name)
    
    print(name)
    model_list.append(name)
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(mse_train))
    print("- Mean Absolute Error: {:.4f}".format(rmse_train))
    print("- R2 Score: {:.4f}".format(r2_train))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(mse_test))
    print("- Mean Absolute Error: {:.4f}".format(rmse_test))
    print("- R2 Score: {:.4f}".format(r2_test))
    r2_list.append(r2_test)
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 4.2013
- Mean Absolute Error: 5.2899
- R2 Score: 0.8799
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.4197
- Mean Absolute Error: 5.4682
- R2 Score: 0.8629
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 5.1510
- Mean Absolute Error: 6.5471
- R2 Score: 0.8160
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.4178
- Mean Absolute Error: 6.8098
- R2 Score: 0.7874
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 4.2006
- Mean Absolute Error: 5.2901
- R2 Score: 0.8799
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.4203
- Mean Absolute Error: 5.4708
- R2 Score: 0.8628
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 4.7493
- Mean Absolute Error: 6.0301
- R2 Score: 0.8439
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.5344
- Mean Absolute Error: 6.9225
- R2 Score: 0.7803
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.0387
- Mean Absolute Error: 0.4626
- R2 Score: 0.9991
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.1520
- Mean Absolute Error: 7.9393
- R2 Score: 0.7110
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 1.7827
- Mean Absolute Error: 2.2956
- R2 Score: 0.9774
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.9100
- Mean Absolute Error: 6.1888
- R2 Score: 0.8244
===================================


XGBRegressor
Model performance for Training set
- Root Mean Squared Error: 0.6178
- Mean Absolute Error: 0.9708
- R2 Score: 0.9960
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.3056
- Mean Absolute Error: 6.7304
- R2 Score: 0.7923
===================================


AdaBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 4.6646
- Mean Absolute Error: 5.7512
- R2 Score: 0.8581
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 4.8707
- Mean Absolute Error: 6.1310
- R2 Score: 0.8277
===================================

In [12]:
pd.DataFrame(list(zip(model_list, r2_list)), columns=['Model Name', 'R2_Score']).sort_values(by=["R2_Score"],ascending=False)

              Model Name  R2_Score
0      Linear Regression  0.862920
2                  Lasso  0.862789
7  K-Neighbors Regressor  0.827674
5                  Ridge  0.824406
6  K-Neighbors Regressor  0.792329
1      Linear Regression  0.787401
3                  Lasso  0.780309
4                  Ridge  0.711030